-- 버전 바뀐후 생성자 추가해야함
-- 밑에 문장은 나는 생성자 추가 안하겠다는 뜻
CREATE ALTER SESSION SET"_ORACLE_SCRIPT" = TRUE;
GRANT CREATE VIEW TO SCOTT;
GRANT CREATE SYNONYM TO SCOTT;

-- 사용자 생성 : system이 권한 부여함
-- CREATE USER 사용자_이름 IDENTIFIED BY 비밀번호
-- DEFAULT TABLESPACE 테이블스페이스명
-- TEMPORARY TABLESPQCE 테이블스페이스 그룹명
-- QUOTA테이블스페이스크기 ON 테이블스페이스명;

-- 공통 사용자 또는 롤 이름이 부적합합니다.
-- 오라클 버전의 변화로 사용자를 생서 시 C## 붙이는걸로 변경됨
CREATE USER TEST1 IDENTIFIED BY 12345
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA 10M ON USERS;

CREATE USER C##TEST1 IDENTIFIED BY 12345
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA 10M ON USERS;
